import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { FileText } from 'lucide-react';

const SECTIONS = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    content: `By accessing or using the ThreadCounty platform ("Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.

ThreadCounty reserves the right to update these Terms at any time. Material changes will be communicated to registered users via email. Continued use of the Service after changes constitutes acceptance of the revised Terms.`
  },
  {
    id: 'account',
    title: '2. Account Responsibilities',
    content: `You are responsible for maintaining the security of your account credentials. Do not share your password with others. ThreadCounty is not liable for any loss resulting from unauthorized access to your account.

You must provide accurate information during registration. Accounts created with false information may be suspended. You must be at least 13 years old to use this Service.

You are responsible for all activity that occurs under your account, including the fabric images you upload and the reports you generate or share.`
  },
  {
    id: 'acceptable-use',
    title: '3. Acceptable Use',
    content: `You agree not to use ThreadCounty for any unlawful purpose or in violation of these Terms. Prohibited uses include:

• Uploading images that contain illegal, harmful, or offensive content unrelated to textile/fabric analysis.
• Attempting to reverse-engineer, scrape, or extract ThreadCounty's AI analysis methodology or model weights.
• Using the Service to perform automated attacks, denial-of-service attempts, or unauthorized access to our infrastructure.
• Creating multiple accounts to circumvent plan limits or abuse the free tier.
• Impersonating another user, administrator, or ThreadCounty staff.

Violations may result in immediate account suspension or termination without notice.`
  },
  {
    id: 'billing',
    title: '4. Subscription & Billing Terms',
    content: `ThreadCounty offers subscription plans (Free, Student, Professional, Enterprise) with varying feature limits. Paid plans are billed on a monthly basis.

Subscription fees are non-refundable except where required by applicable law. You may cancel your subscription at any time from your Profile page — cancellation takes effect at the end of the current billing period, and your account will revert to the Free plan.

Plan pricing may change with 30 days' notice to registered users via email. Grandfathered pricing is not guaranteed.

Note: The current demo deployment uses a mock payment system. No real charges are processed in the demo environment.`
  },
  {
    id: 'ip',
    title: '5. Intellectual Property',
    content: `You retain full ownership of the fabric images you upload. By uploading, you grant ThreadCounty a limited, non-exclusive license to process those images solely for the purpose of generating your analysis reports.

ThreadCounty retains all rights to its AI analysis methodology, software, user interface designs, and brand assets. The analysis reports generated by the platform are provided for your personal or commercial use — you may not resell ThreadCounty's analysis output as a standalone AI service.

The ThreadCounty name, logo, and "ThreadCounty AI" wordmark are trademarks of the ThreadCounty project. Unauthorized use is prohibited.`
  },
  {
    id: 'liability',
    title: '6. Limitation of Liability',
    content: `ThreadCounty provides fabric analysis as an AI-assisted tool and makes no warranty that the analysis results are 100% accurate or suitable for any specific industrial purpose. Results should be verified by a qualified textile professional before being relied upon for production decisions.

To the maximum extent permitted by law, ThreadCounty's total liability for any claim arising from the use of this Service is limited to the amount you paid for the Service in the 3 months preceding the claim.

ThreadCounty is not liable for indirect, incidental, special, or consequential damages, including lost profits or data loss.`
  },
  {
    id: 'termination',
    title: '7. Termination',
    content: `You may delete your account at any time from your Profile → Danger Zone. This permanently removes all your data (uploads, reports, profile) from our systems.

ThreadCounty may suspend or terminate accounts that violate these Terms, with or without prior notice. In cases of serious violations (e.g., abuse, illegal content), immediate termination without refund may apply.`
  },
  {
    id: 'changes',
    title: '8. Changes to Terms',
    content: `We reserve the right to modify these Terms at any time. We will provide at least 14 days' notice for material changes via email and a prominent notice on the platform.

If you disagree with updated Terms, you may close your account before the effective date. Continued use after that date constitutes acceptance.

These Terms are governed by applicable law. Any disputes will be handled through binding arbitration unless prohibited by law.

Last updated: June 24, 2026`
  }
];

export const TermsPage: React.FC = () => {
  const [activeSection, setActiveSection] = useState('acceptance');

  return (
    <div className="min-h-screen bg-white dark:bg-slate-950 py-16 px-4">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12 space-y-3">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-violet-50 dark:bg-violet-950/40 border border-violet-200 dark:border-violet-800 text-violet-600 dark:text-violet-400 text-xs font-bold">
            <FileText className="h-3.5 w-3.5" />
            Legal
          </div>
          <h1 className="text-4xl font-extrabold text-slate-900 dark:text-white">Terms of Service</h1>
          <p className="text-slate-500 text-sm max-w-xl mx-auto">
            Please read these terms carefully before using ThreadCounty. By using the platform you agree to be bound by these terms.
          </p>
          <p className="text-xs text-slate-400">Last updated: June 24, 2026</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-4 gap-10">
          {/* TOC */}
          <nav className="lg:col-span-1 hidden lg:block">
            <div className="sticky top-8 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-4 space-y-1">
              <p className="text-[10px] font-extrabold uppercase tracking-wider text-slate-400 mb-3 px-2">Contents</p>
              {SECTIONS.map(s => (
                <button
                  key={s.id}
                  onClick={() => {
                    setActiveSection(s.id);
                    document.getElementById(s.id)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
                  }}
                  className={`w-full text-left px-3 py-2 rounded-xl text-xs font-semibold transition-all ${
                    activeSection === s.id
                      ? 'bg-violet-50 dark:bg-violet-950/40 text-violet-600 dark:text-violet-400'
                      : 'text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800 hover:text-slate-800 dark:hover:text-white'
                  }`}
                >
                  {s.title}
                </button>
              ))}
            </div>
          </nav>

          {/* Content */}
          <div className="lg:col-span-3 space-y-8">
            {SECTIONS.map(s => (
              <section
                key={s.id}
                id={s.id}
                className="bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 scroll-mt-8"
                onMouseEnter={() => setActiveSection(s.id)}
              >
                <h2 className="font-extrabold text-lg text-slate-800 dark:text-white mb-4">{s.title}</h2>
                <div className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed whitespace-pre-line">
                  {s.content}
                </div>
              </section>
            ))}

            <div className="border border-slate-200 dark:border-slate-800 rounded-2xl p-5 text-center text-sm text-slate-500">
              Questions about these terms? Read our{' '}
              <Link to="/privacy" className="text-violet-600 hover:underline font-semibold">Privacy Policy</Link>{' '}
              or{' '}
              <Link to="/contact" className="text-violet-600 hover:underline font-semibold">contact us</Link>.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsPage;
